""" History reader
History files are generated by writer.history_writer,
and saved under /data/history.

This module is used to read them.
"""
import os
import pickle
from typing import List
from config import Config
from writer.history_writer import HistoryWriter

class HistoryReader:
    """ History reader """
    def __init__(self):
        self._config = Config()

    def get_file_list(self) -> List[str]:
        """ Returns history file list """
        output = []

        for file in os.listdir(self._config.history_dir):
            if file.endswith(HistoryWriter.EXTENSION):
                output.append(file.replace(HistoryWriter.EXTENSION, ""))

        output.sort(reverse=True)
        return output

    def get_performance(self, entry: str):
        """ Returns a performance from history """
        perf_path = os.path.join(self._config.history_dir, entry + HistoryWriter.EXTENSION)
        with open(perf_path, "rb") as sample_pickle:
            perf = pickle.load(sample_pickle)
        return perf
